# Configuration for `pub_rgbd_and_cloud.py`.

ros_topic_namespace: "test_data"
publish_rate: 5.0 # How many data to publish per second.
is_loop_forever: True # After publishing all images, loop back to the 1st one.
frame_id: "head_camera" # Name of the camera frame.

color:
  is_publish: True
  folder: "data/color/" # relatvie to the --base_dir.
  ros_topic: "color"

depth:
  is_publish: True
  folder: "data/depth/" # relatvie to the --base_dir.
  ros_topic: "depth"

  depth_unit: -1 # Doesn't matter.
  depth_trunc: -1 # Doesn't matter.

camera_info:
  is_publish: False
  file: "" # Doesn't matter.
  ros_topic: "" # Doesn't matter.

point_cloud:
  is_publish: False
  ros_topic: "" # Doesn't matter.
